### ISSUE TITLE
Amazing setup!!!

### ISSUE THREAD

**Issue by ghost** [SergioRibera/NvimDotFiles#1]
I have been struggling to build my own set of dotfiles for nvim with little success... yours worked as soon as installed the dependencies.

Two questions though:

how do i get rid of this error:
`[NvimTree] setup.lsp_diagnostics has been removed, see :help nvim-tree.diagnostics`

and now that nvim-compe is being replaced with nvim-cmp (same dude I believe) are you going to remake the dotfiles to work with that instead (I can try to do it myself if not)

Many thanks!

**Comment by ghost** [comment]
also the lua language server in setup is saying it doesn't exist

**Comment by SergioRibera** [comment]
Hey, first of all I greatly appreciate your comment about my configuration, I'm very glad to hear that.

Now, to answer your questions:

- The problem you are getting with NvimTree is because those variables were moved to another place, to fix it I leave you this commit where I [fixed it](https://github.com/SergioRibera/NvimDotFiles/commit/c56878fda1952d828498051a72e0e5c499384b32) and this update note from the [developer](https://github.com/kyazdani42/nvim-tree.lua/issues/674).

- Regarding the migration to nvim-cmp, you caught me by surprise, but I think I will do the migration if needed, now, if you want to do it, go ahead and I will be happy to receive contributions (in case you want to contribute), if not, no problem :D

- Last detail with lua, installing the lua server became a bit more complicated (you have to compile it), but I'm working on a way to do all this automatically to see if that way I can help to make it much easier the whole installation, anyway here are the [instructions](https://github.com/sumneko/lua-language-server/wiki/Build-and-Run-(Standalone))
